layout: {zmk_keyboard: harite_v3}
layers:
  default: [Q, F, W, O, L, U, B, Z, E, D, X, K, Y, H, M, C, I, G, R, V, P, J, ',', ., LCTRL, LALT, LGUI, LSHFT, LSHFT, LGUI, LALT, LCTRL, ESC, sys, '&mkp MB1', '&mkp
      MB3', TAB, num, '&mkp MB2', sym, S, BSPC, A, T, '&key_repeat', SPACE, N, ENTER]
  num:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '!'
  - '|'
  - '*'
  - '&'
  - ;
  - ^
  - /
  - \
  - (
  - )
  - '{'
  - '}'
  - '{'
  - '{'
  - '@'
  - '`'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '-'
  - ''
  - '9'
  - '0'
  - ''
  - {type: held}
  - '='
  - ''
  - $
  - ''
  - '?'
  - '#'
  - ''
  - ''
  - '%'
  - ''
  sym:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  sys:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&bootloader'
  - {t: '&bootloader', type: held}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  '4': ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '']
combos:
- p: [0, 1, 2, 3]
  k: '&studio_unlock'
  l: [default]
- p: [4, 5, 6, 7]
  k: '&studio_unlock'
  l: [default]
- p: [38, 40]
  k: {t: sys, h: toggle}
- p: [39, 41]
  k: {t: sys, h: toggle}
- p: [33, 34]
  k: ESC
