layout: {zmk_keyboard: harite_v3}
layers:
  default:
  - Q
  - F
  - W
  - O
  - L
  - U
  - B
  - Z
  - E
  - D
  - X
  - K
  - Y
  - H
  - M
  - C
  - I
  - G
  - R
  - V
  - P
  - J
  - ','
  - .
  - LCTRL
  - LALT
  - LGUI
  - LSHFT
  - LSHFT
  - LGUI
  - LALT
  - LCTRL
  - ESC
  - {t: sys, h: toggle}
  - '&mkp MB1'
  - '&mkp MB3'
  - TAB
  - num+sym
  - '&mkp MB2'
  - nav
  - S
  - BSPC
  - A
  - T
  - '&key_repeat'
  - SPACE
  - N
  - ENTER
  num+sym:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '!'
  - '|'
  - '*'
  - '&'
  - ;
  - ^
  - /
  - \
  - (
  - )
  - '{'
  - '}'
  - '{'
  - '{'
  - '@'
  - '`'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '-'
  - ''
  - '9'
  - '0'
  - ''
  - {type: held}
  - '='
  - ''
  - $
  - ''
  - '?'
  - '#'
  - ''
  - ''
  - '%'
  - ''
  nav:
  - ''
  - ''
  - ''
  - ''
  - UP
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - LEFT
  - RIGHT
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - DOWN
  - ''
  - ''
  - ''
  - UP
  - ''
  - LEFT
  - RIGHT
  - ''
  - ''
  - DOWN
  - {type: held}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  sys: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '&bootloader', '&bootloader',
    '', '', '', '', '&studio_unlock', '&studio_unlock', '', '', '', '', '', '', '', '']
  '4': ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '']
combos:
- p: [40, 41]
  k: DEL
